// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.6.1
// source: chatCamion/chatCamion.proto

package chatCamion

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PeticionPaquete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TipoCamion string `protobuf:"bytes,1,opt,name=tipoCamion,proto3" json:"tipoCamion,omitempty"`
}

func (x *PeticionPaquete) Reset() {
	*x = PeticionPaquete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatCamion_chatCamion_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeticionPaquete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeticionPaquete) ProtoMessage() {}

func (x *PeticionPaquete) ProtoReflect() protoreflect.Message {
	mi := &file_chatCamion_chatCamion_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeticionPaquete.ProtoReflect.Descriptor instead.
func (*PeticionPaquete) Descriptor() ([]byte, []int) {
	return file_chatCamion_chatCamion_proto_rawDescGZIP(), []int{0}
}

func (x *PeticionPaquete) GetTipoCamion() string {
	if x != nil {
		return x.TipoCamion
	}
	return ""
}

type PaqueteRecibido struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tipo         string `protobuf:"bytes,2,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Valor        string `protobuf:"bytes,3,opt,name=valor,proto3" json:"valor,omitempty"`
	Origen       string `protobuf:"bytes,4,opt,name=origen,proto3" json:"origen,omitempty"`
	Destino      string `protobuf:"bytes,5,opt,name=destino,proto3" json:"destino,omitempty"`
	Intentos     string `protobuf:"bytes,6,opt,name=intentos,proto3" json:"intentos,omitempty"`
	FechaEntrega string `protobuf:"bytes,7,opt,name=fechaEntrega,proto3" json:"fechaEntrega,omitempty"`
	Exito        string `protobuf:"bytes,8,opt,name=exito,proto3" json:"exito,omitempty"`
}

func (x *PaqueteRecibido) Reset() {
	*x = PaqueteRecibido{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatCamion_chatCamion_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaqueteRecibido) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaqueteRecibido) ProtoMessage() {}

func (x *PaqueteRecibido) ProtoReflect() protoreflect.Message {
	mi := &file_chatCamion_chatCamion_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaqueteRecibido.ProtoReflect.Descriptor instead.
func (*PaqueteRecibido) Descriptor() ([]byte, []int) {
	return file_chatCamion_chatCamion_proto_rawDescGZIP(), []int{1}
}

func (x *PaqueteRecibido) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaqueteRecibido) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *PaqueteRecibido) GetValor() string {
	if x != nil {
		return x.Valor
	}
	return ""
}

func (x *PaqueteRecibido) GetOrigen() string {
	if x != nil {
		return x.Origen
	}
	return ""
}

func (x *PaqueteRecibido) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

func (x *PaqueteRecibido) GetIntentos() string {
	if x != nil {
		return x.Intentos
	}
	return ""
}

func (x *PaqueteRecibido) GetFechaEntrega() string {
	if x != nil {
		return x.FechaEntrega
	}
	return ""
}

func (x *PaqueteRecibido) GetExito() string {
	if x != nil {
		return x.Exito
	}
	return ""
}

type PaqueteCompletado struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tipo         string `protobuf:"bytes,2,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Valor        string `protobuf:"bytes,3,opt,name=valor,proto3" json:"valor,omitempty"`
	Origen       string `protobuf:"bytes,4,opt,name=origen,proto3" json:"origen,omitempty"`
	Destino      string `protobuf:"bytes,5,opt,name=destino,proto3" json:"destino,omitempty"`
	Intentos     string `protobuf:"bytes,6,opt,name=intentos,proto3" json:"intentos,omitempty"`
	FechaEntrega string `protobuf:"bytes,7,opt,name=fechaEntrega,proto3" json:"fechaEntrega,omitempty"`
	Exito        string `protobuf:"bytes,8,opt,name=exito,proto3" json:"exito,omitempty"`
}

func (x *PaqueteCompletado) Reset() {
	*x = PaqueteCompletado{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatCamion_chatCamion_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaqueteCompletado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaqueteCompletado) ProtoMessage() {}

func (x *PaqueteCompletado) ProtoReflect() protoreflect.Message {
	mi := &file_chatCamion_chatCamion_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaqueteCompletado.ProtoReflect.Descriptor instead.
func (*PaqueteCompletado) Descriptor() ([]byte, []int) {
	return file_chatCamion_chatCamion_proto_rawDescGZIP(), []int{2}
}

func (x *PaqueteCompletado) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaqueteCompletado) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *PaqueteCompletado) GetValor() string {
	if x != nil {
		return x.Valor
	}
	return ""
}

func (x *PaqueteCompletado) GetOrigen() string {
	if x != nil {
		return x.Origen
	}
	return ""
}

func (x *PaqueteCompletado) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

func (x *PaqueteCompletado) GetIntentos() string {
	if x != nil {
		return x.Intentos
	}
	return ""
}

func (x *PaqueteCompletado) GetFechaEntrega() string {
	if x != nil {
		return x.FechaEntrega
	}
	return ""
}

func (x *PaqueteCompletado) GetExito() string {
	if x != nil {
		return x.Exito
	}
	return ""
}

type MensajeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Respuesta1 string `protobuf:"bytes,1,opt,name=respuesta1,proto3" json:"respuesta1,omitempty"`
}

func (x *MensajeReply) Reset() {
	*x = MensajeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatCamion_chatCamion_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MensajeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MensajeReply) ProtoMessage() {}

func (x *MensajeReply) ProtoReflect() protoreflect.Message {
	mi := &file_chatCamion_chatCamion_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MensajeReply.ProtoReflect.Descriptor instead.
func (*MensajeReply) Descriptor() ([]byte, []int) {
	return file_chatCamion_chatCamion_proto_rawDescGZIP(), []int{3}
}

func (x *MensajeReply) GetRespuesta1() string {
	if x != nil {
		return x.Respuesta1
	}
	return ""
}

var File_chatCamion_chatCamion_proto protoreflect.FileDescriptor

var file_chatCamion_chatCamion_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x63, 0x68, 0x61, 0x74, 0x43, 0x61, 0x6d, 0x69, 0x6f, 0x6e, 0x2f, 0x63, 0x68, 0x61,
	0x74, 0x43, 0x61, 0x6d, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x63,
	0x68, 0x61, 0x74, 0x43, 0x61, 0x6d, 0x69, 0x6f, 0x6e, 0x22, 0x31, 0x0a, 0x0f, 0x50, 0x65, 0x74,
	0x69, 0x63, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x74, 0x69, 0x70, 0x6f, 0x43, 0x61, 0x6d, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x74, 0x69, 0x70, 0x6f, 0x43, 0x61, 0x6d, 0x69, 0x6f, 0x6e, 0x22, 0xd3, 0x01, 0x0a,
	0x0f, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63, 0x69, 0x62, 0x69, 0x64, 0x6f,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x69, 0x70, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72,
	0x69, 0x67, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67,
	0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x12, 0x1a, 0x0a, 0x08,
	0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x6f, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x6f, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x66, 0x65, 0x63, 0x68,
	0x61, 0x45, 0x6e, 0x74, 0x72, 0x65, 0x67, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x66, 0x65, 0x63, 0x68, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x65, 0x67, 0x61, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x78, 0x69, 0x74, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x78, 0x69,
	0x74, 0x6f, 0x22, 0xd5, 0x01, 0x0a, 0x11, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x43, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65,
	0x73, 0x74, 0x69, 0x6e, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x73,
	0x74, 0x69, 0x6e, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x6f, 0x73,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x6f, 0x73,
	0x12, 0x22, 0x0a, 0x0c, 0x66, 0x65, 0x63, 0x68, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x65, 0x67, 0x61,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x65, 0x63, 0x68, 0x61, 0x45, 0x6e, 0x74,
	0x72, 0x65, 0x67, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x69, 0x74, 0x6f, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x78, 0x69, 0x74, 0x6f, 0x22, 0x2e, 0x0a, 0x0c, 0x4d, 0x65,
	0x6e, 0x73, 0x61, 0x6a, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65,
	0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x72, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x31, 0x32, 0xa8, 0x01, 0x0a, 0x0f, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x69, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x12, 0x48,
	0x0a, 0x0c, 0x50, 0x65, 0x64, 0x69, 0x72, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x12, 0x1b,
	0x2e, 0x63, 0x68, 0x61, 0x74, 0x43, 0x61, 0x6d, 0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x65, 0x74, 0x69,
	0x63, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x1a, 0x1b, 0x2e, 0x63, 0x68,
	0x61, 0x74, 0x43, 0x61, 0x6d, 0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x63, 0x69, 0x62, 0x69, 0x64, 0x6f, 0x12, 0x4b, 0x0a, 0x10, 0x43, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x61, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x65, 0x67, 0x61, 0x12, 0x1d, 0x2e, 0x63,
	0x68, 0x61, 0x74, 0x43, 0x61, 0x6d, 0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74,
	0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x61, 0x64, 0x6f, 0x1a, 0x18, 0x2e, 0x63, 0x68,
	0x61, 0x74, 0x43, 0x61, 0x6d, 0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chatCamion_chatCamion_proto_rawDescOnce sync.Once
	file_chatCamion_chatCamion_proto_rawDescData = file_chatCamion_chatCamion_proto_rawDesc
)

func file_chatCamion_chatCamion_proto_rawDescGZIP() []byte {
	file_chatCamion_chatCamion_proto_rawDescOnce.Do(func() {
		file_chatCamion_chatCamion_proto_rawDescData = protoimpl.X.CompressGZIP(file_chatCamion_chatCamion_proto_rawDescData)
	})
	return file_chatCamion_chatCamion_proto_rawDescData
}

var file_chatCamion_chatCamion_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_chatCamion_chatCamion_proto_goTypes = []interface{}{
	(*PeticionPaquete)(nil),   // 0: chatCamion.PeticionPaquete
	(*PaqueteRecibido)(nil),   // 1: chatCamion.PaqueteRecibido
	(*PaqueteCompletado)(nil), // 2: chatCamion.PaqueteCompletado
	(*MensajeReply)(nil),      // 3: chatCamion.MensajeReply
}
var file_chatCamion_chatCamion_proto_depIdxs = []int32{
	0, // 0: chatCamion.ServicioCliente.PedirPaquete:input_type -> chatCamion.PeticionPaquete
	2, // 1: chatCamion.ServicioCliente.CompletarEntrega:input_type -> chatCamion.PaqueteCompletado
	1, // 2: chatCamion.ServicioCliente.PedirPaquete:output_type -> chatCamion.PaqueteRecibido
	3, // 3: chatCamion.ServicioCliente.CompletarEntrega:output_type -> chatCamion.MensajeReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chatCamion_chatCamion_proto_init() }
func file_chatCamion_chatCamion_proto_init() {
	if File_chatCamion_chatCamion_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chatCamion_chatCamion_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeticionPaquete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chatCamion_chatCamion_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaqueteRecibido); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chatCamion_chatCamion_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaqueteCompletado); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chatCamion_chatCamion_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MensajeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chatCamion_chatCamion_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatCamion_chatCamion_proto_goTypes,
		DependencyIndexes: file_chatCamion_chatCamion_proto_depIdxs,
		MessageInfos:      file_chatCamion_chatCamion_proto_msgTypes,
	}.Build()
	File_chatCamion_chatCamion_proto = out.File
	file_chatCamion_chatCamion_proto_rawDesc = nil
	file_chatCamion_chatCamion_proto_goTypes = nil
	file_chatCamion_chatCamion_proto_depIdxs = nil
}
